# Generated by Django 2.2.6 on 2019-10-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infpoolsite', '0002_auto_20191009_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
